### ISSUE TITLE
Config File Directories Content

### ISSUE THREAD

**Issue by drgrib** [3b1b/videos#20]
When I try to run scenes using 

```
manimgl _2022/wordle.py
```

I'm getting an error ending in
```
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/manimlib/utils/file_ops.py", line 47, in find_file
    raise IOError(f"{file_name} not Found")
OSError: /Users/grant/Dropbox/3Blue1Brown/images/pi_creature/svg/plain.svg not Found
```

I understand that I need to change these lines in `custom_config.yml` to point to local content:
```yml
directories:
  mirror_module_path: True
  output: "/Users/grant/Dropbox/3Blue1Brown/videos"
  raster_images: "/Users/grant/Dropbox/3Blue1Brown/images/raster"
  vector_images: "/Users/grant/Dropbox/3Blue1Brown/images/vector"
  pi_creature_images: "/Users/grant/Dropbox/3Blue1Brown/images/pi_creature/svg"
  sounds: "/Users/grant/Dropbox/3Blue1Brown/sounds"
  data: "/Users/grant/Dropbox/3Blue1Brown/data"
  temporary_storage: "/Users/grant/Dropbox/3Blue1Brown/manim_cache"
```

But my question is, point them to what exactly? I can see that other people are able to run `wordle.py` but I have no idea where they got functional content to put in local versions of these directories.
